### ISSUE TITLE
Switch method to POST rather than GET

### ISSUE THREAD

**Issue by jcolfej** [JustAuthMe/PHP-SDK#2]
I wasn't sure where to open this issue, it doesn't directly concern the SDK but the overall implementation of JustAuthMe.

Using GET parameters is less secure than using POST method.
A simple example: parameters are displayed in access logs...

Having the possibility to choose the method used would be a plus, I think...
And make POST as default, like ReCaptcha use it.

**Comment by p-cauty** [comment]
Hi,
There is the "docs" repo for thid kind of issue, but you can open it here as well, we will see it anyway :)

POST over GET isn't semantically correct, as the API request does not post or create anything on the server-side, it is a proper get of an already crafted response.

But you made a point on access logs, we will consider updating the API to accept secrets via request headers.

**Comment by jcolfej** [comment]
Sorry about that...
Do you want I open repost the issue on the doc repository?

I've got a potential other security point that could be tricky.
Why is it necessary to pass the callback url to SDK, as it is known by JAM (in application info)?

**Comment by p-cauty** [comment]
No, here is fine :)
The callback URL in the SDK is usefull in order to, in the future, allow multiple callback URLs. If the security point that concerns you is the spoofing of the callback URL, no worries, we won't redirect the user to an unknown callback.
